#!/usr/bin/env node
// Generate web/party/lib/icons.js: the few Lucide icons the Party pages use, as plain data.
//
//   npm run build:icons        (part of npm run build:ui)
//
// Development-time only. The Pi never runs Node: the generated module is committed, precached by
// the service worker and served by nginx like every other shell file. Add an icon by adding its
// Lucide name to ICONS (https://lucide.dev/icons/) and rebuilding; `npm run check:ui` fails when
// the committed file is stale. Only the listed icons ship, never the whole set.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS = [
  'check', 'chevron-down', 'chevron-left', 'chevron-right', 'circle-alert', 'circle-check', 'circle-help', 'circle-slash',
  'dices', 'eye', 'gamepad-2', 'history', 'image', 'layers', 'lock', 'message-circle', 'monitor', 'play',
  'search', 'search-x', 'send-horizontal', 'smartphone', 'spade', 'star', 'user-round-pen', 'users',
  'wifi', 'wifi-off', 'x',
];

const require = createRequire(import.meta.url);
const pkgDir = path.dirname(require.resolve('lucide-static/package.json'));
const version = JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version;
const ATTR = /([a-z0-9-]+)="([^"]*)"/g;

function nodes(name) {
  const svg = readFileSync(path.join(pkgDir, 'icons', `${name}.svg`), 'utf8');
  const body = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  return [...body.matchAll(/<([a-z]+)\s([^>]*?)\/?>/g)].map(([, tag, attrs]) =>
    [tag, Object.fromEntries([...attrs.matchAll(ATTR)].map(([, k, v]) => [k, v]))]);
}

const data = Object.fromEntries(ICONS.map((name) => [name, nodes(name)]));
const out = `// GENERATED by tools/build-icons.mjs from lucide-static ${version}. Do not edit; run npm run build:icons.
// Lucide icons: ISC License, Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
// part of Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
// https://lucide.dev/license

const ICONS = ${JSON.stringify(data)};
const NS = 'http://www.w3.org/2000/svg';

/** An inline Lucide <svg>. Decorative (aria-hidden) unless a label is given. */
export function icon(name, { label = null, cls = '' } = {}) {
  const svg = document.createElementNS(NS, 'svg');
  const attrs = { viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': '2',
    'stroke-linecap': 'round', 'stroke-linejoin': 'round', class: ('avrana-icon ' + cls).trim(),
    focusable: 'false' };
  for (const [k, v] of Object.entries(attrs)) svg.setAttribute(k, v);
  if (label) { svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', label); }
  else svg.setAttribute('aria-hidden', 'true');
  for (const [tag, props] of ICONS[name] || []) {
    const child = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(props)) child.setAttribute(k, v);
    svg.append(child);
  }
  return svg;
}

/** Fill every <span data-icon="name"> placeholder in static markup (once). */
export function hydrateIcons(root = document) {
  for (const slot of root.querySelectorAll('[data-icon]:empty')) {
    slot.append(icon(slot.dataset.icon, { cls: slot.dataset.iconClass || '' }));
  }
}
`;
const target = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'web', 'party', 'lib', 'icons.js');
if (process.argv.includes('--check')) {
  // Used by tools/check-ui.mjs: compare, never write.
  let current = null;
  try { current = readFileSync(target, 'utf8'); } catch { /* missing counts as stale */ }
  if (current !== out) {
    console.error('web/party/lib/icons.js is stale: run npm run build:icons and commit it');
    process.exit(1);
  }
  console.log('icons.js is current');
} else {
  writeFileSync(target, out);
  console.log(`icons.js: ${ICONS.length} icons, ${out.length} bytes (lucide-static ${version})`);
}
